"""Initial Migration

Revision ID: 033513dac011
Revises: 
Create Date: 2021-11-08 23:53:57.425248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033513dac011'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
